### PR TITLE
automated loading of commands

### PR DESCRIPTION
**Pull request by danthe1st**
This pull request loads commands automatically using the library Reflections.

All classes implementing `Command` in the package `site.purrbot.bot.commands` are automatically added when `CommandLoader` is instantiated.

### CODE REVIEW

**Comment by Andre601** [comment]
Appreciate the effort but I want to stay away from reflection as much as I can as this could become a huge pain in the future. Also Java 11 may complain about Illegal reflection access or whatever, which I also want to avoid as it could get blocked in the future.

**Comment by danthe1st** [comment]
This PR causes no illegal reflective operations as reflection is only used for instantiating constructors. However, it is possible without reflection by creating that class at compile-time.

**Comment by Andre601** [comment]
The way it is right now is fine for me and I have no plans on changing it

**Comment by Andre601** [comment]
Now looking at this will I try to implement it into the bot.
I'll give proper credit to who made this, so don't worry.

**Comment by danthe1st** [comment]
You can also annotate all the commands with an annotation and find all classes annotated with that. You then don't have the compiler warning.

Another method is to create a class loading all the commands at compile-time. The class will reference the other classes and the compiler warning will also not appear.

**Comment by Andre601** [comment]
This wouldn't solve anything as the issue is not errors/warnings on compile-time but that my IDE will complain about the classes being unused, which I do want to avoid.

**Comment by danthe1st** [comment]
The IDE would recognize annotated classes as used, I think.
Also, if it is done at compile-time, a new class is generated that the IDE sees and the IDE warnings will definitely go away.

**Pull request closed without merging**
